---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.4.4
provisioner: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64
    provider: vmware_fusion
    network:
      - ['private_network', {ip: '33.33.33.11'}]
    customize:
      cpus: 2
      numvcpus: 2
      memory: 1024

  run_list:
  - recipe[apt]

- name: ubuntu-13.04
  driver_config:
    box: ubuntu-13.04
    provider: vmware_fusion
    network:
      - ['private_network', {ip: '33.33.33.10'}]
    customize:
      cpus: 2
      numvcpus: 2
      memory: 1024

  run_list:
  - recipe[apt]

suites:
- name: default
  data_bags_path: <%= File.expand_path(File.dirname(__FILE__) + '/data_bags') %>
  run_list:
  - recipe[ruby_build]
  - recipe[<%= File.expand_path('.').split('/').last %>]

  attributes:
<%= File.read('.attributes.yml').gsub(/^/, '    ') if File.exists?('.attributes.yml') %>
